#!/bin/bash

# Define variables
domain=$1
bug_dir=~/bug/$domain
subfinder_subfix=_subfinder
assetfinder_sufix=_assetfinder
subfinder_file="$bug_dir/$domain$subfinder_subfix"
assetfinder_file="$bug_dir/$domain$assetfinder_sufix"
final_file="$bug_dir/"$domain"_final"
sorted_file="$bug_dir/"$domain"_final_sorted"
working_file="$bug_dir/final"
takeover_output="$bug_dir/takeover.txt"

# Define functions
function run_subfinder {
    subfinder -d $domain -t 100 > $subfinder_file
}

function run_assetfinder {
    assetfinder $domain > $assetfinder_file
}

function merge_subdomains {
    cat $subfinder_file $assetfinder_file  > $final_file
}

function filter_duplicates {
    sort -u $final_file > $sorted_file
}

function test_subdomains {
    recce -l -o $working_file < $sorted_file
}

function take_over {
    takeover -l ~/bug/$domain/final -t 100 > $takeover_output
    }

# Check for input parameter
if [[ ! -n $domain ]]; then
    echo "No domain parameter passed."
    exit 1
fi

# Create bug directory
mkdir $bug_dir

# Run tools and pipe to xargs
run_subfinder&
run_assetfinder&
wait

# sorting then merging then filtering to make powerful sub-domains list
merge_subdomains&
filter_duplicates&
wait

# scaning for alive sub-domain and then scaing for sub-domain takeover
test_subdomains&
wait
take_over&
wait

# Clean up intermediate files
rm -f $subfinder_file $haktrails_file $assetfinder_file $final_file $sorted_file
